RangeTool: util::UniqueRangeSet< T > Class Template Reference
util::UniqueRangeSet< T > Class Template Reference
std::set of util::Range, which does not allow any overlap in contained element.
#include <Range.h>
Public Member Functions
UniqueRangeSet ()
default ctor
~UniqueRangeSet ()
default dtor
void Merge (const UniqueRangeSet< T > &in)
Merge two UniqueRangeSet<T>
const T & Start () const
Very first "start" of all contained range.
const T & End () const
Very first "start" of all contained range.
UniqueRangeSet< T > Exclusive (const T start, const T end) const
It takes two input arguments, "start" and "end", and returns util::UniqueRangeSet
of all exclusive regions between "start" and "end".
size_t emplace (const T &start, const T &end)
Modified emplace that merges overlapping range. Return = # merged range.
size_t insert (const Range< T > &a)
Modified insert that merges overlapping range. Return = # merged range.
Public Attributes
K keys
STL member.
Detailed Description
template<class T>
class util::UniqueRangeSet< T >
std::set of util::Range, which does not allow any overlap in contained element.
std::set<Range> w/ modified insert/emplace function. Original std::set does not allow
modification of element. I assume what we're interested in is "find if the range already \n exists, and merge if it exists". The insert function does that by recursively looking up
overlapping elements w.r.t. input argument of insert function.
One important function worth noting is util::UniqueRangeSet::Exclusive which takes two
input arguments, "start" and "end", and returns util::UniqueRangeSet of all exclusive
regions between "start" and "end". By definition, merging this return with the original
instance will result in 1 huge util::Range.
Definition at line 23 of file Range.h.
Constructor & Destructor Documentation
template<class T> util::UniqueRangeSet< T >::UniqueRangeSet () inline
default ctor
Definition at line 41 of file UniqueRangeSet.h.
 {}
template<class T> util::UniqueRangeSet< T >::~UniqueRangeSet () inline
default dtor
Definition at line 43 of file UniqueRangeSet.h.
 {}
Member Function Documentation
template<class T> size_t util::UniqueRangeSet< T >::emplace (const T & start, const T & end) inline
Modified emplace that merges overlapping range. Return = # merged range.
Definition at line 96 of file UniqueRangeSet.h.
References util::UniqueRangeSet< T >::insert(), and util::Range< T >::Merge().
Referenced by util::range::bmark_exclude(), util::range::bmark_insert(), util::UniqueRangeSet< T >::insert(), util::UniqueRangeSet< T >::Merge(), and util::range::test_overlap().
{
       auto res = std::set<util::Range<T> >::emplace(start,end);
       if(res.second) return 0;
       auto& iter = res.first;
       auto tmp_a = Range<T>(start,end);
       size_t ctr=0;
       while(iter != this->end()) {
     tmp_a.Merge((*iter));
     this->erase(iter);
     iter = this->find(tmp_a);
     ++ctr;
       }
       this->insert(tmp_a);
       return ctr;
     }
template<class T> const T& util::UniqueRangeSet< T >::End () const inline
Very first "start" of all contained range.
Definition at line 57 of file UniqueRangeSet.h.
     {
       if(!(this->size())) throw std::runtime_error("Nothing in the set!");
       return (*(this->rbegin()))._window.second;
     }
template<class T> UniqueRangeSet<T> util::UniqueRangeSet< T >::Exclusive (const T start, const T end) const inline
It takes two input arguments, "start" and "end", and returns util::UniqueRangeSet
of all exclusive regions between "start" and "end".
By definition, merging this
return with the original instance will result in 1 huge util::Range.
Definition at line 68 of file UniqueRangeSet.h.
Referenced by util::range::bmark_exclude(), and util::range::test_overlap().
     {
       UniqueRangeSet<T> res;
       auto start_iter = std::lower_bound(this->begin(),this->end(),start);
       auto end_iter   = std::lower_bound(this->begin(),this->end(),end);
       // Anything to add to the head?
       if(start < (*start_iter)._window.first) res.emplace(start,(*start_iter)._window.first);
       auto iter = start_iter;
       T  tmp_end=end;
       while(iter != this->end()) {
     if(iter != start_iter)
       res.emplace(tmp_end,(*iter)._window.first);
     tmp_end   = (*iter)._window.second;
     if(iter == end_iter) break;
     ++iter;
       }
       // Anything to add to the tail?
       if(tmp_end < end)
     res.emplace(tmp_end,end);
       return res;
     }
template<class T> size_t util::UniqueRangeSet< T >::insert (const Range< T > & a) inline
Modified insert that merges overlapping range. Return = # merged range.
Definition at line 115 of file UniqueRangeSet.h.
References util::Range< T >::_window, and util::UniqueRangeSet< T >::emplace().
Referenced by util::UniqueRangeSet< T >::emplace().
     {return emplace(a._window.first,a._window.second);}
template<class T> void util::UniqueRangeSet< T >::Merge (const UniqueRangeSet< T > & in) inline
Merge two UniqueRangeSet<T>
Definition at line 46 of file UniqueRangeSet.h.
References util::UniqueRangeSet< T >::emplace().
     { for(auto const& r : in) emplace(r._window.first,r._window.second); }
template<class T> const T& util::UniqueRangeSet< T >::Start () const inline
Very first "start" of all contained range.
Definition at line 50 of file UniqueRangeSet.h.
     {
       if(!(this->size())) throw std::runtime_error("Nothing in the set!");
       return (*(this->begin()))._window.first;
     }
Member Data Documentation
K std::set< K >::keys inherited
STL member.
The documentation for this class was generated from the following files:
Range.h
UniqueRangeSet.h