RangeTool: util::range Namespace Reference
util::range Namespace Reference
namespace to contain functions that involve util::Range and util::UniqueRangeSet
Enumerations
enum MergeErrorType_t { kMergeNoError, kMergeInclusive, kMergeHalfOverlap, kMergeExclusive }
Error type for inspecting merging.
Functions
double bmark_insert (const size_t nentries)
bench-mark func: for util::UniqueRangeSet::Insert function
double bmark_exclude (const size_t nentries)
bench-mark func: for util::Range::Exclude
MergeErrorType_t test_overlap ()
testing overlap
Detailed Description
namespace to contain functions that involve util::Range and util::UniqueRangeSet
Enumeration Type Documentation
enum util::range::MergeErrorType_t
Error type for inspecting merging.
Enumerator
kMergeNoError
no error
kMergeInclusive
failed to merge a large range w/ small
kMergeHalfOverlap
failed to merge two overlapping range (but not inclusive)
kMergeExclusive
failed to perform util::UniqueRangeSet::Exclude properly
Definition at line 18 of file range_test.h.
{
       kMergeNoError,
       kMergeInclusive,
       kMergeHalfOverlap,
       kMergeExclusive
     };
Function Documentation
double util::range::bmark_exclude (const size_t nentries)
bench-mark func: for util::Range::Exclude
Definition at line 22 of file range_test.cxx.
References util::UniqueRangeSet< T >::emplace(), and util::UniqueRangeSet< T >::Exclusive().
     {
       UniqueRangeSet<double> sample;
       for(size_t i=0; i<nentries; ++i)
     sample.emplace((double)(4*i),(double)(4*i+1));
       auto const& start = (*sample.begin()).Start();
       auto const& end   = (*sample.rbegin()).End();
       clock_t time_start = clock();
       auto res = sample.Exclusive( (start - (end - start)*0.1),
                    (end + (end - start)*0.1) );
       clock_t time_end = clock();
       if( res.size() != (nentries + 1) ) return -1;
       return ((double)(time_end - time_start))/CLOCKS_PER_SEC;
     }
double util::range::bmark_insert (const size_t nentries)
bench-mark func: for util::UniqueRangeSet::Insert function
Definition at line 12 of file range_test.cxx.
References util::UniqueRangeSet< T >::emplace().
     {
       UniqueRangeSet<size_t> range_set;
       clock_t time_start = clock();
       for(size_t i=0; i<nentries; ++i)
     range_set.emplace(4*i,4*i+3);
       clock_t time_sum = clock() - time_start;
       return (range_set.size() == nentries ? ((double)time_sum)/CLOCKS_PER_SEC : -1);
     }
MergeErrorType_t util::range::test_overlap ()
testing overlap
Definition at line 39 of file range_test.cxx.
References util::UniqueRangeSet< T >::emplace(), util::Range< T >::End(), util::UniqueRangeSet< T >::Exclusive(), kMergeExclusive, kMergeHalfOverlap, kMergeInclusive, kMergeNoError, util::Range< T >::Merge(), and util::Range< T >::Start().
     {
       // Test inclusive overlap
       Range<size_t> small(10,20);
       Range<size_t> large(0,30);
       small.Merge(large);
       if(small != large) return kMergeInclusive;
       // Test half-overlap
       Range<size_t> head(10,20);
       Range<size_t> tail(15,25);
       head.Merge(tail);
       if( head.Start() != 10 || head.End() !=25 ) return kMergeHalfOverlap;
       // Test UniqueRangeSet::Exclusive
       UniqueRangeSet<size_t> range_set;
       for(size_t i=0; i<10; ++i)
     range_set.emplace(4*i, (4*i+4));
       auto start = (*range_set.begin()).Start();
       auto end   = (*range_set.rbegin()).End();
       auto ex_range_set = range_set.Exclusive(start,end);
       if(ex_range_set.size()) return kMergeExclusive;
       range_set.clear();
       ex_range_set.clear();
       for(size_t i=0; i<10; ++i)
     range_set.emplace(4*i, (4*i+3));
       start = (*range_set.begin()).Start();
       end   = (*range_set.rbegin()).End();
       ex_range_set = range_set.Exclusive(start,end);
       if( range_set.size() != (ex_range_set.size()+1) ) return kMergeExclusive;
       ex_range_set.Merge(range_set);
       if( ex_range_set.size() != 1 ) return kMergeExclusive;
       return kMergeNoError;
     }